version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root 
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - proxy
      - wordpress 

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wordpress

  proxy:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    restart: always
    user: root
    command: -e -E cloud.id="${ELASTIC_CLOUD_ID}" -E cloud.auth="${ELASTIC_CLOUD_AUTH}"
    volumes:
      - ./conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

# TODO: find a better way...
  getip:
    image: curlimages/curl
    restart: "no"
    user: root
    command: -s checkip.amazonaws.com
    

volumes:
  wordpress:
  db:

networks:
  proxy:
  wordpress:
    internal: yes
